// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.collaboraonline.mattermost",
  "name": "Collabora Online",
  "description": "Allows users to edit/view documents with the help of Collabora Online",
  "version": "1.1.0",
  "min_server_version": "5.11.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "WOPIAddress",
        "display_name": "Collabora Online address",
        "type": "text",
        "help_text": "Collabora Online address. Please see https://www.collaboraoffice.com/integrations/mattermost-plugin/ for more information.",
        "placeholder": "URL",
        "default": ""
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
